In [4]:
!pip install pandas numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
numbers = pd.DataFrame(np.arange(0,90,3).reshape(10,3), index=['row 1','row 2','row 3','row 4','row 5','row 6','row 7','row 8','row 9','row 10'], columns=['Column A', 'Column B', 'Column C'])
numbers

        Column A  Column B  Column C
row 1          0         3         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

In [16]:
numbers.iloc[0,1]
numbers.iloc[[0,2],[0,2]]

       Column A  Column C
row 1         0         6
row 3        18        24

In [15]:
numbers.loc['row 1','Column B']

np.int64(3)

In [1]:
data = {'names':['steve','john','richard','sarah','randy','micheal','julie'],
        'age':[20,22,20,21,24,23,22],
        'gender':['Male','Male','Male','Female','Male','Male','Female'],
        'rank':[2,1,4,5,3,7,6]}

In [8]:
data = {'names':['steve','john','richard','sarah','randy','micheal','julie'],
        'age':[20,22,20,21,24,23,22],
        'gender':['Male','Male','Male','Female','Male','Male','Female'],
        'rank':[2,1,4,5,3,7,6]}

ranking_df = pd.DataFrame(data)
ranking_df.iloc[2:5,1]= np.nan
ranking_df.iloc[3:6,3]= np.nan
ranking_df.iloc[3,:]= np.nan
ranking_df

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [10]:
ranking_df.notnull() 
ranking_df.isnull()

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [13]:
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

     names  age gender  rank
2  richard  NaN   Male   4.0
3      NaN  NaN    NaN   NaN
4    randy  NaN   Male   NaN

In [14]:
ranking_df.fillna(0)

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   0.0    Male   4.0
3        0   0.0       0   0.0
4    randy   0.0    Male   0.0
5  micheal  23.0    Male   0.0
6    julie  22.0  Female   6.0

In [15]:
ranking_df.fillna(method='pad')

/tmp/ipykernel_1652/2647120121.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ranking_df.fillna(method='pad')

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard  22.0    Male   4.0
3  richard  22.0    Male   4.0
4    randy  22.0    Male   4.0
5  micheal  23.0    Male   4.0
6    julie  22.0  Female   6.0

In [16]:
ranking_df.interpolate(method='linear')

/tmp/ipykernel_1652/4007689601.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ranking_df.interpolate(method='linear')

     names    age  gender  rank
0    steve  20.00    Male   2.0
1     john  22.00    Male   1.0
2  richard  22.25    Male   4.0
3      NaN  22.50     NaN   4.5
4    randy  22.75    Male   5.0
5  micheal  23.00    Male   5.5
6    julie  22.00  Female   6.0

In [18]:
ranking_df.dropna()

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0

In [19]:
ranking_df.dropna(how='all')

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [21]:
ranking_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [23]:
DF_obj = pd.DataFrame({'column 1': [1,1,2,2,3,3,3],
                    'column 2':['a', 'a', 'b', 'b', 'c', 'c', 'c'],
                    'column 3': ['A', 'A', 'B', 'B', 'C', 'C', 'C']})
DF_obj

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        C

In [24]:
DF_obj.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [25]:
DF_obj.drop_duplicates()

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: age, dtype: bool